### ISSUE TITLE
[Improve][CI] Imrpove trigger conditons in the stable workflow

### ISSUE THREAD

**Issue by shink** [apache/incubator-inlong#4024]
### Description

Imrpove trigger conditons in the stable workflow.

```yaml
days-before-issue-stale: 30       # the idle number of days before marking the issues as stale
days-before-pr-stale: 45          # the idle number of days before marking the pull requests as stale
days-before-issue-close: 5        # the idle number of days before closing the stale issues
days-before-pr-close: 10          # the idle number of days before closing the stale pull requests
```

--->

```yaml
days-before-issue-stale: 60       # the idle number of days before marking the issues as stale
days-before-pr-stale: 60          # the idle number of days before marking the pull requests as stale
days-before-issue-close: 30        # the idle number of days before closing the stale issues
days-before-pr-close: 30          # the idle number of days before closing the stale pull requests
```

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
